# Generated by Django 6.0.1 on 2026-01-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(choices=[('butwal', 'Butwal'), ('pokhara', 'Pokhara'), ('kathmandu', 'Kathmandu'), ('bhaktapur', 'Bhaktapur'), ('lalitpur', 'Lalitpur')], default='kathmandu', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('primaryMood', models.CharField(choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], default='relax', max_length=50)),
                ('secondaryMood', models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], default='nature', max_length=50)),
                ('tertiaryMood', models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], default='food', max_length=50)),
                ('quaternaryMood', models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], default='adventure', max_length=50)),
                ('primaryWeather', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy')], default='sunny', max_length=50)),
                ('secondaryWeather', models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy')], default='cloudy', max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
