# Generated by Django 6.0.1 on 2026-01-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('bhaktapur', 'Bhaktapur'), ('lalitpur', 'Lalitpur')], default='kathmandu', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('primary_mood', models.CharField(choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize')], max_length=20)),
                ('secondary_mood', models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize')], max_length=20, null=True)),
                ('min_budget', models.IntegerField(help_text='Minimum budget in NPR')),
                ('max_budget', models.IntegerField(help_text='Maximum budget in NPR')),
                ('min_time_hours', models.FloatField(help_text='Minimum time needed in hours')),
                ('max_time_hours', models.FloatField(help_text='Maximum time for a visit in hours')),
                ('environment', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
