# Generated by Django 6.0.1 on 2026-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('kathmandu', 'Kathmandu'), ('pokhara', 'Pokhara'), ('bhaktapur', 'Bhaktapur'), ('lalitpur', 'Lalitpur'), ('butwal', 'Butwal')], default='kathmandu', max_length=50),
        ),
    ]
