# Generated by Django 6.0.1 on 2026-01-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='environment',
        ),
        migrations.AddField(
            model_name='place',
            name='primary_weather',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy')], default='sunny', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='quaternary_mood',
            field=models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='secondary_weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tertiary_mood',
            field=models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='primary_mood',
            field=models.CharField(choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='secondary_mood',
            field=models.CharField(blank=True, choices=[('relax', 'Relax'), ('adventure', 'Adventure'), ('food', 'Food'), ('nature', 'Nature'), ('socialize', 'Socialize'), ('shopping', 'Shopping')], max_length=20, null=True),
        ),
    ]
