# Generated by Django 6.0.1 on 2026-01-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_environment_place_primary_weather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_url',
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
