# Generated by Django 6.0.1 on 2026-01-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
